import { Court } from "@/models/types";

// will need 50 >
const courts: Court[] = [
  {
    id: 1,
    name: "Central Park Tennis Center",
    location: "New York, NY",
    surface: "Clay",
    indoor: false,
    lighting: true,
    court_num: 26,
    access: "Paid",
    price: "$15/hour",
    amenities: ["Locker rooms", "Pro shop", "Water fountains"],
    parking: "Street parking",
    img: "/images/courts/centralpark.jpg",
    rating: 4.5,
    review_count: 120,
  },
  {
    id: 2,
    name: "Riverside Community Courts",
    location: "New York, NY",
    surface: "Hard",
    indoor: false,
    lighting: false,
    court_num: 8,
    access: "Free",
    price: "Free",
    amenities: ["Benches", "Restrooms"],
    parking: "Street",
    img: "/images/courts/riverside.jpg",
    rating: 3.8,
    review_count: 45,
  },
  {
    id: 3,
    name: "Skyline Indoor Tennis",
    location: "Chicago, IL",
    surface: "Hard",
    indoor: true,
    lighting: true,
    court_num: 6,
    access: "Paid",
    price: "$25/hour",
    amenities: ["Locker rooms", "Showers", "Pro shop"],
    parking: "Garage",
    img: "/images/courts/skyline.jpg",
    rating: 4.7,
    review_count: 88,
  },
  {
    id: 4,
    name: "Bayview Park Courts",
    location: "Miami, FL",
    surface: "Clay",
    indoor: false,
    lighting: false,
    court_num: 4,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Water fountains"],
    parking: "Street and lot",
    img: "/images/courts/bayview.jpg",
    rating: 3.2,
    review_count: 22,
  },
  {
    id: 5,
    name: "Highland Racquet Club",
    location: "Atlanta, GA",
    surface: "Hard",
    indoor: true,
    lighting: true,
    court_num: 12,
    access: "Membership",
    price: "$70/month",
    amenities: ["Gym", "Cafe", "Pro shop"],
    parking: "Large lot",
    img: "/images/courts/highland.jpg",
    rating: 4.8,
    review_count: 190,
  },
  {
    id: 6,
    name: "Westwood Community Courts",
    location: "Los Angeles, CA",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 10,
    access: "Free",
    price: "Free",
    amenities: ["Water fountains", "Restrooms"],
    parking: "On-site lot",
    img: "/images/courts/westwood.jpg",
    rating: 4.0,
    review_count: 76,
  },
  {
    id: 7,
    name: "Lakewood Park Courts",
    location: "Seattle, WA",
    surface: "Synthetic Grass",
    indoor: false,
    lighting: true,
    court_num: 5,
    access: "Free",
    price: "Free",
    amenities: ["Bike racks", "Picnic tables"],
    parking: "Street",
    img: "/images/courts/lakewood.jpg",
    rating: 4.3,
    review_count: 53,
  },
  {
    id: 8,
    name: "Harbor Point Club",
    location: "San Francisco, CA",
    surface: "Carpet",
    indoor: true,
    lighting: true,
    court_num: 3,
    access: "Membership",
    price: "$120/month",
    amenities: ["Lounge", "Bar", "Locker rooms"],
    parking: "Valet",
    img: "/images/courts/harborpoint.jpg",
    rating: 4.9,
    review_count: 61,
  },
  {
    id: 9,
    name: "Desert Dunes Sports Complex",
    location: "Phoenix, AZ",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 10,
    access: "Paid",
    price: "$10/hour",
    amenities: ["Snack bar", "Shaded seating"],
    parking: "Large lot",
    img: "/images/courts/desertdunes.jpg",
    rating: 4.4,
    review_count: 84,
  },
  {
    id: 10,
    name: "Lincoln Park Courts",
    location: "Chicago, IL",
    surface: "Hard",
    indoor: false,
    lighting: false,
    court_num: 12,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Water fountains"],
    parking: "Street",
    img: "/images/courts/lincoln.jpg",
    rating: 3.9,
    review_count: 40,
  },
  {
    id: 11,
    name: "Sunset Tennis Club",
    location: "Los Angeles, CA",
    surface: "Hard",
    indoor: true,
    lighting: true,
    court_num: 8,
    access: "Paid",
    price: "$20/hour",
    amenities: ["Cafe", "Locker rooms", "Showers"],
    parking: "Garage",
    img: "/images/courts/sunset.jpg",
    rating: 4.6,
    review_count: 72,
  },
  {
    id: 12,
    name: "Greenfield Community Courts",
    location: "Austin, TX",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 6,
    access: "Free",
    price: "Free",
    amenities: ["Water fountains", "Restrooms"],
    parking: "Lot",
    img: "/images/courts/greenfield.jpg",
    rating: 4.1,
    review_count: 28,
  },
  {
    id: 13,
    name: "Cedar Grove Sports Complex",
    location: "Dallas, TX",
    surface: "Clay",
    indoor: false,
    lighting: true,
    court_num: 10,
    access: "Paid",
    price: "$12/hour",
    amenities: ["Snack bar", "Seating", "Locker rooms"],
    parking: "Large lot",
    img: "/images/courts/cedargrove.jpg",
    rating: 4.2,
    review_count: 59,
  },
  {
    id: 14,
    name: "Golden Gate Park Tennis Courts",
    location: "San Francisco, CA",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 21,
    access: "Paid",
    price: "$8/hour",
    amenities: ["Pro shop", "Locker rooms"],
    parking: "Street",
    img: "/images/courts/goldengate.jpg",
    rating: 4.5,
    review_count: 134,
  },
  {
    id: 15,
    name: "Brooklyn Bridge Courts",
    location: "Brooklyn, NY",
    surface: "Hard",
    indoor: false,
    lighting: false,
    court_num: 4,
    access: "Free",
    price: "Free",
    amenities: ["Benches", "Restrooms"],
    parking: "Street",
    img: "/images/courts/brooklynbridge.jpg",
    rating: 3.7,
    review_count: 25,
  },
  {
    id: 16,
    name: "Palm Grove Racquet Club",
    location: "Miami, FL",
    surface: "Clay",
    indoor: true,
    lighting: true,
    court_num: 10,
    access: "Membership",
    price: "$90/month",
    amenities: ["Cafe", "Showers", "Gym"],
    parking: "Valet",
    img: "/images/courts/palmgrove.jpg",
    rating: 4.9,
    review_count: 102,
  },
  {
    id: 17,
    name: "Southside Community Courts",
    location: "Houston, TX",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 6,
    access: "Free",
    price: "Free",
    amenities: ["Water fountains", "Restrooms"],
    parking: "Street",
    img: "/images/courts/southside.jpg",
    rating: 3.9,
    review_count: 33,
  },
  {
    id: 18,
    name: "Pacific Shores Tennis Club",
    location: "San Diego, CA",
    surface: "Synthetic Grass",
    indoor: false,
    lighting: true,
    court_num: 12,
    access: "Paid",
    price: "$18/hour",
    amenities: ["Cafe", "Locker rooms", "Pro shop"],
    parking: "Lot",
    img: "/images/courts/pacificshores.jpg",
    rating: 4.6,
    review_count: 81,
  },
  {
    id: 19,
    name: "Oakwood Racquet Club",
    location: "Boston, MA",
    surface: "Clay",
    indoor: true,
    lighting: true,
    court_num: 7,
    access: "Membership",
    price: "$75/month",
    amenities: ["Cafe", "Gym", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/oakwood.jpg",
    rating: 4.7,
    review_count: 110,
  },
  {
    id: 20,
    name: "Capitol Hill Courts",
    location: "Washington, DC",
    surface: "Hard",
    indoor: false,
    lighting: false,
    court_num: 6,
    access: "Free",
    price: "Free",
    amenities: ["Benches", "Restrooms"],
    parking: "Street",
    img: "/images/courts/capitolhill.jpg",
    rating: 3.5,
    review_count: 19,
  },
  {
    id: 21,
    name: "Liberty Park Courts",
    location: "Salt Lake City, UT",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 8,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Water fountains"],
    parking: "Lot",
    img: "/images/courts/liberty.jpg",
    rating: 4.0,
    review_count: 27,
  },
  {
    id: 22,
    name: "Evergreen Racquet Club",
    location: "Portland, OR",
    surface: "Synthetic Grass",
    indoor: true,
    lighting: true,
    court_num: 10,
    access: "Membership",
    price: "$80/month",
    amenities: ["Cafe", "Gym", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/evergreen.jpg",
    rating: 4.6,
    review_count: 92,
  },
  {
    id: 23,
    name: "Civic Center Courts",
    location: "Denver, CO",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 12,
    access: "Free",
    price: "Free",
    amenities: ["Benches", "Restrooms"],
    parking: "Street",
    img: "/images/courts/civic.jpg",
    rating: 4.1,
    review_count: 39,
  },
  {
    id: 24,
    name: "Desert Palms Club",
    location: "Palm Springs, CA",
    surface: "Clay",
    indoor: false,
    lighting: true,
    court_num: 6,
    access: "Paid",
    price: "$15/hour",
    amenities: ["Pro shop", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/desertpalms.jpg",
    rating: 4.3,
    review_count: 55,
  },
  {
    id: 25,
    name: "Bayfront Community Courts",
    location: "Tampa, FL",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 10,
    access: "Free",
    price: "Free",
    amenities: ["Water fountains", "Restrooms"],
    parking: "Lot",
    img: "/images/courts/bayfront.jpg",
    rating: 3.9,
    review_count: 31,
  },
  {
    id: 26,
    name: "Rocky Ridge Tennis Center",
    location: "Boulder, CO",
    surface: "Hard",
    indoor: true,
    lighting: true,
    court_num: 8,
    access: "Paid",
    price: "$18/hour",
    amenities: ["Cafe", "Showers", "Pro shop"],
    parking: "Lot",
    img: "/images/courts/rockyridge.jpg",
    rating: 4.5,
    review_count: 64,
  },
  {
    id: 27,
    name: "Harborview Courts",
    location: "Baltimore, MD",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 12,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Benches"],
    parking: "Street",
    img: "/images/courts/harborview.jpg",
    rating: 3.7,
    review_count: 21,
  },
  {
    id: 28,
    name: "Forest Hills Club",
    location: "Queens, NY",
    surface: "Grass",
    indoor: false,
    lighting: true,
    court_num: 4,
    access: "Membership",
    price: "$150/month",
    amenities: ["Lounge", "Cafe", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/foresthills.jpg",
    rating: 4.9,
    review_count: 133,
  },
  {
    id: 29,
    name: "Shoreline Park Courts",
    location: "Santa Monica, CA",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 6,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Benches"],
    parking: "Street",
    img: "/images/courts/shoreline.jpg",
    rating: 4.2,
    review_count: 42,
  },
  {
    id: 30,
    name: "Summit Tennis Academy",
    location: "Denver, CO",
    surface: "Hard",
    indoor: true,
    lighting: true,
    court_num: 12,
    access: "Paid",
    price: "$22/hour",
    amenities: ["Gym", "Cafe", "Showers"],
    parking: "Lot",
    img: "/images/courts/summit.jpg",
    rating: 4.8,
    review_count: 97,
  },
  {
    id: 31,
    name: "Riverwalk Courts",
    location: "San Antonio, TX",
    surface: "Hard",
    indoor: false,
    lighting: false,
    court_num: 6,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Water fountains"],
    parking: "Street",
    img: "/images/courts/riverwalk.jpg",
    rating: 3.6,
    review_count: 18,
  },
  {
    id: 32,
    name: "Pinecrest Racquet Club",
    location: "Orlando, FL",
    surface: "Clay",
    indoor: true,
    lighting: true,
    court_num: 8,
    access: "Membership",
    price: "$85/month",
    amenities: ["Cafe", "Pro shop", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/pinecrest.jpg",
    rating: 4.7,
    review_count: 104,
  },
  {
    id: 33,
    name: "Northside Community Courts",
    location: "Minneapolis, MN",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 10,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Water fountains"],
    parking: "Lot",
    img: "/images/courts/northside.jpg",
    rating: 3.8,
    review_count: 29,
  },
  {
    id: 34,
    name: "Silver Lake Club",
    location: "Cleveland, OH",
    surface: "Clay",
    indoor: false,
    lighting: true,
    court_num: 6,
    access: "Paid",
    price: "$12/hour",
    amenities: ["Cafe", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/silverlake.jpg",
    rating: 4.4,
    review_count: 46,
  },
  {
    id: 35,
    name: "Sunrise Park Courts",
    location: "Las Vegas, NV",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 12,
    access: "Free",
    price: "Free",
    amenities: ["Water fountains", "Restrooms"],
    parking: "Lot",
    img: "/images/courts/sunrise.jpg",
    rating: 4.0,
    review_count: 38,
  },
  {
    id: 36,
    name: "Redwood Racquet Club",
    location: "San Jose, CA",
    surface: "Hard",
    indoor: true,
    lighting: true,
    court_num: 12,
    access: "Membership",
    price: "$95/month",
    amenities: ["Gym", "Cafe", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/redwood.jpg",
    rating: 4.6,
    review_count: 111,
  },
  {
    id: 37,
    name: "Bluewater Courts",
    location: "San Diego, CA",
    surface: "Synthetic Grass",
    indoor: false,
    lighting: true,
    court_num: 8,
    access: "Paid",
    price: "$14/hour",
    amenities: ["Snack bar", "Restrooms"],
    parking: "Lot",
    img: "/images/courts/bluewater.jpg",
    rating: 4.2,
    review_count: 56,
  },
  {
    id: 38,
    name: "East River Courts",
    location: "New York, NY",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 10,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Water fountains"],
    parking: "Street",
    img: "/images/courts/eastriver.jpg",
    rating: 3.9,
    review_count: 43,
  },
  {
    id: 39,
    name: "Maplewood Racquet Club",
    location: "Philadelphia, PA",
    surface: "Clay",
    indoor: true,
    lighting: true,
    court_num: 9,
    access: "Membership",
    price: "$85/month",
    amenities: ["Gym", "Cafe", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/maplewood.jpg",
    rating: 4.5,
    review_count: 97,
  },
  {
    id: 40,
    name: "Canyon View Courts",
    location: "Colorado Springs, CO",
    surface: "Hard",
    indoor: false,
    lighting: false,
    court_num: 6,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms"],
    parking: "Lot",
    img: "/images/courts/canyonview.jpg",
    rating: 3.4,
    review_count: 16,
  },
  {
    id: 41,
    name: "Sunset Bay Club",
    location: "Honolulu, HI",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 12,
    access: "Paid",
    price: "$20/hour",
    amenities: ["Cafe", "Pro shop"],
    parking: "Lot",
    img: "/images/courts/sunsetbay.jpg",
    rating: 4.8,
    review_count: 84,
  },
  {
    id: 42,
    name: "Golden Sands Courts",
    location: "San Diego, CA",
    surface: "Clay",
    indoor: false,
    lighting: true,
    court_num: 10,
    access: "Paid",
    price: "$15/hour",
    amenities: ["Locker rooms", "Cafe"],
    parking: "Lot",
    img: "/images/courts/goldensands.jpg",
    rating: 4.3,
    review_count: 58,
  },
  {
    id: 43,
    name: "Lakeside Park Courts",
    location: "Madison, WI",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 6,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Benches"],
    parking: "Street",
    img: "/images/courts/lakeside.jpg",
    rating: 3.8,
    review_count: 22,
  },
  {
    id: 44,
    name: "Riverbend Racquet Club",
    location: "Cincinnati, OH",
    surface: "Hard",
    indoor: true,
    lighting: true,
    court_num: 10,
    access: "Membership",
    price: "$90/month",
    amenities: ["Cafe", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/riverbend.jpg",
    rating: 4.7,
    review_count: 115,
  },
  {
    id: 45,
    name: "Desert Valley Courts",
    location: "Phoenix, AZ",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 12,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Water fountains"],
    parking: "Lot",
    img: "/images/courts/desertvalley.jpg",
    rating: 4.0,
    review_count: 37,
  },
  {
    id: 46,
    name: "Hilltop Racquet Club",
    location: "Nashville, TN",
    surface: "Clay",
    indoor: true,
    lighting: true,
    court_num: 8,
    access: "Membership",
    price: "$75/month",
    amenities: ["Gym", "Cafe", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/hilltop.jpg",
    rating: 4.5,
    review_count: 101,
  },
  {
    id: 47,
    name: "Greenway Courts",
    location: "Raleigh, NC",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 6,
    access: "Free",
    price: "Free",
    amenities: ["Restrooms", "Benches"],
    parking: "Lot",
    img: "/images/courts/greenway.jpg",
    rating: 3.9,
    review_count: 29,
  },
  {
    id: 48,
    name: "Meadowbrook Club",
    location: "Detroit, MI",
    surface: "Hard",
    indoor: true,
    lighting: true,
    court_num: 12,
    access: "Membership",
    price: "$85/month",
    amenities: ["Gym", "Cafe", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/meadowbrook.jpg",
    rating: 4.6,
    review_count: 95,
  },
  {
    id: 49,
    name: "Pioneer Park Courts",
    location: "Portland, OR",
    surface: "Hard",
    indoor: false,
    lighting: false,
    court_num: 4,
    access: "Free",
    price: "Free",
    amenities: ["Benches"],
    parking: "Street",
    img: "/images/courts/pioneer.jpg",
    rating: 3.5,
    review_count: 14,
  },
  {
    id: 50,
    name: "Seaside Racquet Club",
    location: "Santa Cruz, CA",
    surface: "Hard",
    indoor: false,
    lighting: true,
    court_num: 8,
    access: "Paid",
    price: "$20/hour",
    amenities: ["Cafe", "Pro shop", "Locker rooms"],
    parking: "Lot",
    img: "/images/courts/seaside.jpg",
    rating: 4.7,
    review_count: 120,
  },
];

export default courts;
