import { Review } from "@/models/types";

const reviews: Review[] = [
  {
    id: 1,
    court_id: 1,
    user: "tennisFan92",
    rating: 5,
    comment:
      "Beautiful clay courts, well maintained. A bit crowded on weekends.",
    date: "2025-07-10",
  },
  {
    id: 2,
    court_id: 1,
    user: "claylover",
    rating: 4,
    comment: "Great location in Central Park, but reservations are pricey.",
    date: "2025-08-02",
  },
  {
    id: 3,
    court_id: 2,
    user: "sunsetplayer",
    rating: 4,
    comment: "Love playing here in the evenings. Lights work great!",
    date: "2025-07-18",
  },
  {
    id: 4,
    court_id: 2,
    user: "casualswing",
    rating: 3,
    comment: "Good community courts but surface has cracks in some spots.",
    date: "2025-09-01",
  },
  {
    id: 5,
    court_id: 3,
    user: "indoorking",
    rating: 5,
    comment: "Best indoor courts in Chicago. Worth the hourly rate.",
    date: "2025-08-22",
  },
  {
    id: 6,
    court_id: 4,
    user: "miamitennis",
    rating: 2,
    comment: "Free, but surfaces are worn down. No lights for night play.",
    date: "2025-06-29",
  },
  {
    id: 7,
    court_id: 5,
    user: "clubpro",
    rating: 5,
    comment: "Amazing facility with gym and cafe. Pricey but worth it.",
    date: "2025-08-10",
  },
  {
    id: 8,
    court_id: 5,
    user: "atlantaforehand",
    rating: 4,
    comment: "Great courts but sometimes hard to book during peak hours.",
    date: "2025-09-03",
  },
  {
    id: 9,
    court_id: 6,
    user: "pnwplayer",
    rating: 4,
    comment: "Love the green synthetic surface. Great for casual matches.",
    date: "2025-07-27",
  },
  {
    id: 10,
    court_id: 7,
    user: "desertsmash",
    rating: 5,
    comment: "Well lit and spacious. Perfect for evening play in Phoenix.",
    date: "2025-08-15",
  },
  {
    id: 11,
    court_id: 8,
    user: "bayareabackhand",
    rating: 5,
    comment: "Luxury club vibe. Carpet courts play very fast!",
    date: "2025-07-30",
  },
  {
    id: 12,
    court_id: 8,
    user: "netrusher",
    rating: 4,
    comment: "Great indoor experience, but expensive membership.",
    date: "2025-08-28",
  },
  {
    id: 13,
    court_id: 1,
    rating: 5,
    comment: "Fantastic clay courts, very well maintained!",
    date: "2025-07-10",
    user: "tennisFan92",
  },
  {
    id: 14,
    court_id: 1,
    rating: 4,
    comment: "Great location, sometimes crowded on weekends.",
    date: "2025-07-12",
    user: "claylover",
  },
  {
    id: 15,
    court_id: 2,
    rating: 3,
    comment: "Good courts but some cracks in the surface.",
    date: "2025-07-15",
    user: "casualswing",
  },
  {
    id: 16,
    court_id: 2,
    rating: 4,
    comment: "Nice community courts, enjoy playing here.",
    date: "2025-07-18",
    user: "sunsetplayer",
  },
  {
    id: 17,
    court_id: 3,
    rating: 5,
    comment: "Indoor facility is excellent, worth the fee.",
    date: "2025-07-20",
    user: "indoorking",
  },
  {
    id: 18,
    court_id: 3,
    rating: 4,
    comment: "Courts are very clean and organized.",
    date: "2025-07-22",
    user: "hardcourtpro",
  },
  {
    id: 19,
    court_id: 4,
    rating: 2,
    comment: "Free courts, but surfaces are worn out.",
    date: "2025-07-25",
    user: "miamitennis",
  },
  {
    id: 20,
    court_id: 5,
    rating: 5,
    comment: "Amazing facility, great amenities for members.",
    date: "2025-07-27",
    user: "clubpro",
  },
  {
    id: 21,
    court_id: 5,
    rating: 4,
    comment: "Booking can be tough during peak hours.",
    date: "2025-07-29",
    user: "atlantaforehand",
  },
  {
    id: 22,
    court_id: 6,
    rating: 4,
    comment: "Good public courts, well lit at night.",
    date: "2025-07-30",
    user: "westwoodplayer",
  },
  {
    id: 23,
    court_id: 7,
    rating: 4,
    comment: "Synthetic grass is fun to play on, casual vibe.",
    date: "2025-08-01",
    user: "pnwplayer",
  },
  {
    id: 24,
    court_id: 8,
    rating: 5,
    comment: "Luxury club with excellent courts and fast play.",
    date: "2025-08-03",
    user: "bayareabackhand",
  },
  {
    id: 25,
    court_id: 8,
    rating: 4,
    comment: "Nice experience but pricey membership.",
    date: "2025-08-05",
    user: "netrusher",
  },
  {
    id: 26,
    court_id: 9,
    rating: 5,
    comment: "Spacious courts with good evening lighting.",
    date: "2025-08-07",
    user: "desertsmash",
  },
  {
    id: 27,
    court_id: 9,
    rating: 4,
    comment: "Very good courts, snack bar is a nice touch.",
    date: "2025-08-10",
    user: "sunsetplayer2",
  },
  {
    id: 28,
    court_id: 10,
    rating: 3,
    comment: "Good location, surfaces need maintenance.",
    date: "2025-08-12",
    user: "lincolnplayer",
  },
  {
    id: 29,
    court_id: 10,
    rating: 4,
    comment: "Pleasant experience, quiet during weekdays.",
    date: "2025-08-14",
    user: "quietrally",
  },
  {
    id: 30,
    court_id: 11,
    rating: 5,
    comment: "Indoor courts are top-notch, highly recommended.",
    date: "2025-08-16",
    user: "sunsetclub",
  },
  {
    id: 31,
    court_id: 11,
    rating: 4,
    comment: "Good lighting and facility.",
    date: "2025-08-18",
    user: "clubenthusiast",
  },
  {
    id: 32,
    court_id: 12,
    rating: 4,
    comment: "Community courts, perfect for beginners.",
    date: "2025-08-20",
    user: "greenfieldplayer",
  },
  {
    id: 33,
    court_id: 12,
    rating: 3,
    comment: "Nice courts but parking is limited.",
    date: "2025-08-22",
    user: "parkedout",
  },
  {
    id: 34,
    court_id: 13,
    rating: 4,
    comment: "Clay courts are smooth and enjoyable.",
    date: "2025-08-24",
    user: "cedarlover",
  },
  {
    id: 35,
    court_id: 13,
    rating: 5,
    comment: "Snack bar and seating are great.",
    date: "2025-08-26",
    user: "rallyking",
  },
  {
    id: 36,
    court_id: 14,
    rating: 4,
    comment: "Great facility, easy to book.",
    date: "2025-08-28",
    user: "goldengatefan",
  },
  {
    id: 37,
    court_id: 14,
    rating: 5,
    comment: "Very well maintained courts.",
    date: "2025-08-30",
    user: "courtlove",
  },
];

export default reviews;
